kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
  labels:
    password: grupo1
secretGenerator:
- name: mysql-pass
  literals:
  - password=grupo1
resources:
  - wp.yaml
  - wordpress-deployment.yaml
  - mysql-deployment.yaml
