kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: mysql-pass
  literals:
  - password="grupo1"
resources:
  - wp.yaml
  - wordpress-deployment.yaml
  - mysql-deployment.yaml
